<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/home.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
	<div id="app">
		<h1>FAYDE: Jamais Vue</h1>
		<p> An experimental Vue port of the FAYDE on Air. </p>
    <p>{{ message }}</p>
  </div>
</template>

<script>
// import store from '@/store'
export default {
  data: function() {
    return {
      // sharedState: store.state,
      message: "Hello home!"
    };
  },
  watch: {
    onCreated: function(response) {
      this.items = response.data;
    }
  },
  methods: {
    //Add the button to your template: <button @click="onClick">click this</button>
    onClick: function() {
      console.log("clicked");
    }
  },
  computed: {}
  // props: {},
  // components: {},
  // mixins: [],
  // directives: {},
  // filters: {},
  // asyncComputed: {},
};
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
