# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50635e03f55820c9493b318ad0072d0bc87fb190add962255bac5be5f98e18526867f9f1492c91b6ec76d03d5406f5d3c44d91980464f4c620b9f6e0fc802e72

test:
  secret_key_base: 5fd6bf6754639e1e0897c7c1e592be133ce42e2d29b38b0f4edf770bf6612bae8f8c02a1e5cfe7e353a0c9c4c267309c6570411cbf7e99ab66f28db704c5ead3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
